dist: xenial
language: ruby
sudo: true
cache: bundler

git:
  depth: 50

rvm:
  - 2.6.3
services:
  - postgresql
  - redis-server

matrix:
  include:
    - rvm: 2.5.3
      name: 'RuboCop (for changed files)'
      if: branch != master
      script:
        - echo "$(git --no-pager diff --name-only $TRAVIS_COMMIT_RANGE)" | xargs bundle exec rubocop "$@"

    - rvm: 2.5.3
      name: 'Perform DB setup (with seeds)'
      before_script:
        - cp config/database.yml.sample config/database.yml
      script:
        - bundle exec rake db:setup

    - rvm: 2.5.3
      name: 'Tests'
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      before_install:
        - sudo apt-get update
        - sudo apt-get install chromium-chromedriver
      before_script:
        - export PATH=$PATH:/usr/lib/chromium-browser/
        - cp config/database.yml.sample config/database.yml
        - cp .env.test .env
        - bundle exec rake db:create
        - bundle exec rake db:schema:load
      script:
        - bundle exec rspec
